test: woaini
app.datasource.bar.url: jdbc:oracle:thin:@134.32.30.131:3521:sibil4db
app.datasource.bar.username: ucr_bil_acct
app.datasource.bar.password: SI_shaoyong123
app.datasource.bar.driver-class-name: oracle.jdbc.driver.OracleDriver
app.datasource.actdb1.url: jdbc:oracle:thin:@(description: (LOAD_BALANCE :  off)(FAILOVER :  on)(address:  (protocol: tcp)(host: 134.32.28.55)(port: 1523))(address:  (protocol: tcp)(host: 134.32.28.56)(port: 1523))(connect_data:  (service_name: act1db)(failover_mode: (type: select)(method: basic)(backup: act1db2_tux)(retries: 20)(delay: 20))))
app.datasource.actdb1.username: si_shaoyong
app.datasource.actdb1.password: stc_xiao9672
app.datasource.actdb1.driver-class-name: oracle.jdbc.driver.OracleDriver
app.datasource.actdb2.url: jdbc:oracle:thin:@(description: (LOAD_BALANCE :  off)(FAILOVER :  on)(address:  (protocol: tcp)(host: 134.32.28.57)(port: 1523))(address:  (protocol: tcp)(host: 134.32.28.58)(port: 1523))(connect_data:  (service_name: act2db)(failover_mode: (type: select)(method: basic)(backup: act2db2_tux)(retries: 20)(delay: 20))))
app.datasource.actdb2.username: si_shaoyong
app.datasource.actdb2.password: stc_xiao9672
app.datasource.actdb2.driver-class-name: oracle.jdbc.driver.OracleDriver
app.datasource.actdb3.url: jdbc:oracle:thin:@(description: (LOAD_BALANCE :  off)(FAILOVER :  on)(address:  (protocol: tcp)(host: 134.32.28.56)(port: 1523))(address:  (protocol: tcp)(host: 134.32.28.55)(port: 1523))(connect_data:  (service_name: act3db)(failover_mode: (type: select)(method: basic)(backup: act3db2_tux)(retries: 20)(delay: 20))))
app.datasource.actdb3.username: si_shaoyong
app.datasource.actdb3.password: stc_xiao9672
app.datasource.actdb3.driver-class-name: oracle.jdbc.driver.OracleDriver
app.datasource.actdb4.url: jdbc:oracle:thin:@ (description: (LOAD_BALANCE :  off)(FAILOVER :  on)(address:  (protocol: tcp)(host: 134.32.28.58)(port: 1523))(address:  (protocol: tcp)(host: 134.32.28.57)(port: 1523))(connect_data:  (service_name: act4db)(failover_mode: (type: select)(method: basic)(backup: act4db2_tux)(retries: 20)(delay: 20))))
app.datasource.actdb4.username: si_shaoyong
app.datasource.actdb4.password: stc_xiao9672
app.datasource.actdb4.driver-class-name: oracle.jdbc.driver.OracleDriver
app.datasource.actdb6.url: jdbc:oracle:thin:@ (DESCRIPTION :  (ADDRESS :  (PROTOCOL :  TCP)(HOST :  134.32.10.113)(PORT :  1521)) (CONNECT_DATA :  (SERVER :  DEDICATED)  (SID :  jihe) )     )
app.datasource.actdb6.username: bill_check
app.datasource.actdb6.password: stcxiao7799
app.datasource.actdb6.driver-class-name: oracle.jdbc.driver.OracleDriver
